// Danh sách các cặp từ đồng âm (Homophones) phổ biến trong tiếng Anh
// giúp tránh việc chấm điểm sai khi trình duyệt nhận diện nhầm từ đồng âm.
export const HOMOPHONES_MAP: Record<string, string[]> = {
  "meet": ["meat", "mete"],
  "meat": ["meet", "mete"],
  "see": ["sea", "c"],
  "sea": ["see", "c"],
  "tea": ["tee"],
  "tee": ["tea"],
  "blue": ["blew"],
  "blew": ["blue"],
  "four": ["for", "fore"],
  "for": ["four", "fore"],
  "here": ["hear"],
  "hear": ["here"],
  "there": ["their", "they're"],
  "their": ["there", "they're"],
  "no": ["know"],
  "know": ["no"],
  "so": ["sew", "sow"],
  "sew": ["so", "sow"],
  "red": ["read"],
  "read": ["red"],
  "weak": ["week"],
  "week": ["weak"],
  "son": ["sun"],
  "sun": ["son"],
  "right": ["write", "rite"],
  "write": ["right", "rite"],
  "bye": ["by", "buy"],
  "by": ["bye", "buy"],
  "buy": ["bye", "by"],
  "too": ["to", "two"],
  "to": ["too", "two"],
  "two": ["too", "to"],
  "new": ["knew"],
  "knew": ["new"],
  "our": ["hour"],
  "hour": ["our"],
  "flour": ["flower"],
  "flower": ["flour"],
  "be": ["bee"],
  "bee": ["be"],
  "some": ["sum"],
  "sum": ["some"],
  "ad": ["add"],
  "add": ["ad"],
  "board": ["bored"],
  "bored": ["board"],
  "brake": ["break"],
  "break": ["brake"],
  "cell": ["sell"],
  "sell": ["cell"],
  "deer": ["dear"],
  "dear": ["deer"],
  "die": ["dye"],
  "dye": ["die"],
  "fair": ["fare"],
  "fare": ["fair"],
  "heal": ["heel"],
  "heel": ["heal"],
  "hole": ["whole"],
  "whole": ["hole"],
  "idle": ["idol"],
  "idol": ["idle"],
  "its": ["it's"],
  "it's": ["its"],
  "mail": ["male"],
  "male": ["mail"],
  "pair": ["pear"],
  "pear": ["pair"],
  "piece": ["peace"],
  "peace": ["piece"],
  "plain": ["plane"],
  "plane": ["plain"],
  "sail": ["sale"],
  "sale": ["sail"],
  "stare": ["stair"],
  "stair": ["stare"],
  "steal": ["steel"],
  "steel": ["steal"],
  "tail": ["tale"],
  "tale": ["tail"],
  "waste": ["waist"],
  "waist": ["waste"],
  "way": ["weigh"],
  "weigh": ["way"],
};
